server:
  port: 8082

kafka-settings:
  kafka-server: ${KAFKA_BROKER_URL:127.0.0.1:29092}
  topic-name: ${TOPIC-NAME:topic2}

spring:
  data:
    mongodb:
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}
      database: ${MONGO_DATABASE:sex-shop}
      username: ${MONGO_USERNAME:dbuser}
      password: ${MONGO_PASSWORD:dbpassword}
      authentication-database: ${MONGO_AUTH:admin}